version: '3.8'

services:
  php:
    depends_on:
      - db
    build:
      context: ./docker/php
      target: base
    environment:
      APACHE_RUN_USER: www-data
      TZ: Europe/Budapest
    ports:
      - "80:80"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/virtualhost.conf:/etc/apache2/sites-enabled/virtualhost.conf:ro
      - .:/var/www/html

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: Europe/Budapest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
